/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayRouteImport } from './routes/play'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as ViewIdRouteImport } from './routes/view.$id'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as ApiPublicMediaProxyRouteImport } from './routes/api/public/media-proxy'
import { Route as ApiPublicPlayRouteImport } from './routes/api/public/play'
import { Route as ApiPublicStreamRouteImport } from './routes/api/public/stream'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIdRoute = ViewIdRouteImport.update({
  id: '/view/$id',
  path: '/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaProxyRoute = ApiPublicMediaProxyRouteImport.update({
  id: '/api/public/media-proxy',
  path: '/api/public/media-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlayRoute = ApiPublicPlayRouteImport.update({
  id: '/api/public/play',
  path: '/api/public/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamRoute = ApiPublicStreamRouteImport.update({
  id: '/api/public/stream',
  path: '/api/public/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/item/$id': typeof ItemIdRoute
  '/view/$id': typeof ViewIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/play': typeof ApiPublicPlayRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/item/$id': typeof ItemIdRoute
  '/view/$id': typeof ViewIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/play': typeof ApiPublicPlayRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/item/$id': typeof ItemIdRoute
  '/view/$id': typeof ViewIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/play': typeof ApiPublicPlayRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/library'
    | '/login'
    | '/play'
    | '/search'
    | '/settings'
    | '/upgrade'
    | '/checkout/return'
    | '/item/$id'
    | '/view/$id'
    | '/watch/$id'
    | '/api/public/media-proxy'
    | '/api/public/play'
    | '/api/public/stream'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/library'
    | '/login'
    | '/play'
    | '/search'
    | '/settings'
    | '/upgrade'
    | '/checkout/return'
    | '/item/$id'
    | '/view/$id'
    | '/watch/$id'
    | '/api/public/media-proxy'
    | '/api/public/play'
    | '/api/public/stream'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/library'
    | '/login'
    | '/play'
    | '/search'
    | '/settings'
    | '/upgrade'
    | '/checkout/return'
    | '/item/$id'
    | '/view/$id'
    | '/watch/$id'
    | '/api/public/media-proxy'
    | '/api/public/play'
    | '/api/public/stream'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UpgradeRoute: typeof UpgradeRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ItemIdRoute: typeof ItemIdRoute
  ViewIdRoute: typeof ViewIdRoute
  WatchIdRoute: typeof WatchIdRoute
  ApiPublicMediaProxyRoute: typeof ApiPublicMediaProxyRoute
  ApiPublicPlayRoute: typeof ApiPublicPlayRoute
  ApiPublicStreamRoute: typeof ApiPublicStreamRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$id': {
      id: '/view/$id'
      path: '/view/$id'
      fullPath: '/view/$id'
      preLoaderRoute: typeof ViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-proxy': {
      id: '/api/public/media-proxy'
      path: '/api/public/media-proxy'
      fullPath: '/api/public/media-proxy'
      preLoaderRoute: typeof ApiPublicMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/play': {
      id: '/api/public/play'
      path: '/api/public/play'
      fullPath: '/api/public/play'
      preLoaderRoute: typeof ApiPublicPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream': {
      id: '/api/public/stream'
      path: '/api/public/stream'
      fullPath: '/api/public/stream'
      preLoaderRoute: typeof ApiPublicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UpgradeRoute: UpgradeRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ItemIdRoute: ItemIdRoute,
  ViewIdRoute: ViewIdRoute,
  WatchIdRoute: WatchIdRoute,
  ApiPublicMediaProxyRoute: ApiPublicMediaProxyRoute,
  ApiPublicPlayRoute: ApiPublicPlayRoute,
  ApiPublicStreamRoute: ApiPublicStreamRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
